// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConversationProtobuf.proto

package stsquestbuilder.protocolbuffers;

public final class ConversationProtobuf {
  private ConversationProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConversationPackageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .Conversation conversations = 1;
    java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation> 
        getConversationsList();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation getConversations(int index);
    int getConversationsCount();
    java.util.List<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder> 
        getConversationsOrBuilderList();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder getConversationsOrBuilder(
        int index);
  }
  public static final class ConversationPackage extends
      com.google.protobuf.GeneratedMessage
      implements ConversationPackageOrBuilder {
    // Use ConversationPackage.newBuilder() to construct.
    private ConversationPackage(Builder builder) {
      super(builder);
    }
    private ConversationPackage(boolean noInit) {}
    
    private static final ConversationPackage defaultInstance;
    public static ConversationPackage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConversationPackage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationPackage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationPackage_fieldAccessorTable;
    }
    
    // repeated .Conversation conversations = 1;
    public static final int CONVERSATIONS_FIELD_NUMBER = 1;
    private java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation> conversations_;
    public java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation> getConversationsList() {
      return conversations_;
    }
    public java.util.List<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder> 
        getConversationsOrBuilderList() {
      return conversations_;
    }
    public int getConversationsCount() {
      return conversations_.size();
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation getConversations(int index) {
      return conversations_.get(index);
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder getConversationsOrBuilder(
        int index) {
      return conversations_.get(index);
    }
    
    private void initFields() {
      conversations_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getConversationsCount(); i++) {
        if (!getConversations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < conversations_.size(); i++) {
        output.writeMessage(1, conversations_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < conversations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, conversations_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationPackage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationPackage_fieldAccessorTable;
      }
      
      // Construct using stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConversationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (conversationsBuilder_ == null) {
          conversations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          conversationsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage.getDescriptor();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage getDefaultInstanceForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage.getDefaultInstance();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage build() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage buildPartial() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage result = new stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage(this);
        int from_bitField0_ = bitField0_;
        if (conversationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            conversations_ = java.util.Collections.unmodifiableList(conversations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.conversations_ = conversations_;
        } else {
          result.conversations_ = conversationsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage) {
          return mergeFrom((stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage other) {
        if (other == stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage.getDefaultInstance()) return this;
        if (conversationsBuilder_ == null) {
          if (!other.conversations_.isEmpty()) {
            if (conversations_.isEmpty()) {
              conversations_ = other.conversations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConversationsIsMutable();
              conversations_.addAll(other.conversations_);
            }
            onChanged();
          }
        } else {
          if (!other.conversations_.isEmpty()) {
            if (conversationsBuilder_.isEmpty()) {
              conversationsBuilder_.dispose();
              conversationsBuilder_ = null;
              conversations_ = other.conversations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              conversationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConversationsFieldBuilder() : null;
            } else {
              conversationsBuilder_.addAllMessages(other.conversations_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getConversationsCount(); i++) {
          if (!getConversations(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder subBuilder = stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addConversations(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .Conversation conversations = 1;
      private java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation> conversations_ =
        java.util.Collections.emptyList();
      private void ensureConversationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          conversations_ = new java.util.ArrayList<stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation>(conversations_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder> conversationsBuilder_;
      
      public java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation> getConversationsList() {
        if (conversationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(conversations_);
        } else {
          return conversationsBuilder_.getMessageList();
        }
      }
      public int getConversationsCount() {
        if (conversationsBuilder_ == null) {
          return conversations_.size();
        } else {
          return conversationsBuilder_.getCount();
        }
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation getConversations(int index) {
        if (conversationsBuilder_ == null) {
          return conversations_.get(index);
        } else {
          return conversationsBuilder_.getMessage(index);
        }
      }
      public Builder setConversations(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation value) {
        if (conversationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConversationsIsMutable();
          conversations_.set(index, value);
          onChanged();
        } else {
          conversationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setConversations(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder builderForValue) {
        if (conversationsBuilder_ == null) {
          ensureConversationsIsMutable();
          conversations_.set(index, builderForValue.build());
          onChanged();
        } else {
          conversationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addConversations(stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation value) {
        if (conversationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConversationsIsMutable();
          conversations_.add(value);
          onChanged();
        } else {
          conversationsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addConversations(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation value) {
        if (conversationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConversationsIsMutable();
          conversations_.add(index, value);
          onChanged();
        } else {
          conversationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addConversations(
          stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder builderForValue) {
        if (conversationsBuilder_ == null) {
          ensureConversationsIsMutable();
          conversations_.add(builderForValue.build());
          onChanged();
        } else {
          conversationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addConversations(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder builderForValue) {
        if (conversationsBuilder_ == null) {
          ensureConversationsIsMutable();
          conversations_.add(index, builderForValue.build());
          onChanged();
        } else {
          conversationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllConversations(
          java.lang.Iterable<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation> values) {
        if (conversationsBuilder_ == null) {
          ensureConversationsIsMutable();
          super.addAll(values, conversations_);
          onChanged();
        } else {
          conversationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearConversations() {
        if (conversationsBuilder_ == null) {
          conversations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          conversationsBuilder_.clear();
        }
        return this;
      }
      public Builder removeConversations(int index) {
        if (conversationsBuilder_ == null) {
          ensureConversationsIsMutable();
          conversations_.remove(index);
          onChanged();
        } else {
          conversationsBuilder_.remove(index);
        }
        return this;
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder getConversationsBuilder(
          int index) {
        return getConversationsFieldBuilder().getBuilder(index);
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder getConversationsOrBuilder(
          int index) {
        if (conversationsBuilder_ == null) {
          return conversations_.get(index);  } else {
          return conversationsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder> 
           getConversationsOrBuilderList() {
        if (conversationsBuilder_ != null) {
          return conversationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(conversations_);
        }
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder addConversationsBuilder() {
        return getConversationsFieldBuilder().addBuilder(
            stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.getDefaultInstance());
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder addConversationsBuilder(
          int index) {
        return getConversationsFieldBuilder().addBuilder(
            index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.getDefaultInstance());
      }
      public java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder> 
           getConversationsBuilderList() {
        return getConversationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder> 
          getConversationsFieldBuilder() {
        if (conversationsBuilder_ == null) {
          conversationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation, stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder>(
                  conversations_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          conversations_ = null;
        }
        return conversationsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ConversationPackage)
    }
    
    static {
      defaultInstance = new ConversationPackage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ConversationPackage)
  }
  
  public interface ConversationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ConversationNode root = 1;
    boolean hasRoot();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode getRoot();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder getRootOrBuilder();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string creator = 3;
    boolean hasCreator();
    String getCreator();
  }
  public static final class Conversation extends
      com.google.protobuf.GeneratedMessage
      implements ConversationOrBuilder {
    // Use Conversation.newBuilder() to construct.
    private Conversation(Builder builder) {
      super(builder);
    }
    private Conversation(boolean noInit) {}
    
    private static final Conversation defaultInstance;
    public static Conversation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Conversation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Conversation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Conversation_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .ConversationNode root = 1;
    public static final int ROOT_FIELD_NUMBER = 1;
    private stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode root_;
    public boolean hasRoot() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode getRoot() {
      return root_;
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder getRootOrBuilder() {
      return root_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string creator = 3;
    public static final int CREATOR_FIELD_NUMBER = 3;
    private java.lang.Object creator_;
    public boolean hasCreator() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          creator_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      root_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
      name_ = "";
      creator_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRoot()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRoot().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, root_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCreatorBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, root_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCreatorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Conversation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Conversation_fieldAccessorTable;
      }
      
      // Construct using stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRootFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (rootBuilder_ == null) {
          root_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
        } else {
          rootBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        creator_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.getDescriptor();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation getDefaultInstanceForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.getDefaultInstance();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation build() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation buildPartial() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation result = new stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (rootBuilder_ == null) {
          result.root_ = root_;
        } else {
          result.root_ = rootBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.creator_ = creator_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation) {
          return mergeFrom((stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation other) {
        if (other == stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.getDefaultInstance()) return this;
        if (other.hasRoot()) {
          mergeRoot(other.getRoot());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasCreator()) {
          setCreator(other.getCreator());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRoot()) {
          
          return false;
        }
        if (!getRoot().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder subBuilder = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.newBuilder();
              if (hasRoot()) {
                subBuilder.mergeFrom(getRoot());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRoot(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              creator_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ConversationNode root = 1;
      private stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode root_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder> rootBuilder_;
      public boolean hasRoot() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode getRoot() {
        if (rootBuilder_ == null) {
          return root_;
        } else {
          return rootBuilder_.getMessage();
        }
      }
      public Builder setRoot(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode value) {
        if (rootBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          root_ = value;
          onChanged();
        } else {
          rootBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setRoot(
          stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder builderForValue) {
        if (rootBuilder_ == null) {
          root_ = builderForValue.build();
          onChanged();
        } else {
          rootBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeRoot(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode value) {
        if (rootBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              root_ != stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance()) {
            root_ =
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.newBuilder(root_).mergeFrom(value).buildPartial();
          } else {
            root_ = value;
          }
          onChanged();
        } else {
          rootBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearRoot() {
        if (rootBuilder_ == null) {
          root_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
          onChanged();
        } else {
          rootBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder getRootBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRootFieldBuilder().getBuilder();
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder getRootOrBuilder() {
        if (rootBuilder_ != null) {
          return rootBuilder_.getMessageOrBuilder();
        } else {
          return root_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder> 
          getRootFieldBuilder() {
        if (rootBuilder_ == null) {
          rootBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder>(
                  root_,
                  getParentForChildren(),
                  isClean());
          root_ = null;
        }
        return rootBuilder_;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string creator = 3;
      private java.lang.Object creator_ = "";
      public boolean hasCreator() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCreator(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        creator_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreator() {
        bitField0_ = (bitField0_ & ~0x00000004);
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      void setCreator(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        creator_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Conversation)
    }
    
    static {
      defaultInstance = new Conversation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Conversation)
  }
  
  public interface ConversationNodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string text = 1;
    boolean hasText();
    String getText();
    
    // repeated .Connection connections = 2;
    java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection> 
        getConnectionsList();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection getConnections(int index);
    int getConnectionsCount();
    java.util.List<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder> 
        getConnectionsOrBuilderList();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder getConnectionsOrBuilder(
        int index);
  }
  public static final class ConversationNode extends
      com.google.protobuf.GeneratedMessage
      implements ConversationNodeOrBuilder {
    // Use ConversationNode.newBuilder() to construct.
    private ConversationNode(Builder builder) {
      super(builder);
    }
    private ConversationNode(boolean noInit) {}
    
    private static final ConversationNode defaultInstance;
    public static ConversationNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConversationNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationNode_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .Connection connections = 2;
    public static final int CONNECTIONS_FIELD_NUMBER = 2;
    private java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection> connections_;
    public java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection> getConnectionsList() {
      return connections_;
    }
    public java.util.List<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder> 
        getConnectionsOrBuilderList() {
      return connections_;
    }
    public int getConnectionsCount() {
      return connections_.size();
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection getConnections(int index) {
      return connections_.get(index);
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder getConnectionsOrBuilder(
        int index) {
      return connections_.get(index);
    }
    
    private void initFields() {
      text_ = "";
      connections_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getConnectionsCount(); i++) {
        if (!getConnections(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      for (int i = 0; i < connections_.size(); i++) {
        output.writeMessage(2, connections_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      for (int i = 0; i < connections_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, connections_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationNode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_ConversationNode_fieldAccessorTable;
      }
      
      // Construct using stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConnectionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (connectionsBuilder_ == null) {
          connections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          connectionsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDescriptor();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode getDefaultInstanceForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode build() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode buildPartial() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode result = new stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        if (connectionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            connections_ = java.util.Collections.unmodifiableList(connections_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.connections_ = connections_;
        } else {
          result.connections_ = connectionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode) {
          return mergeFrom((stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode other) {
        if (other == stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        if (connectionsBuilder_ == null) {
          if (!other.connections_.isEmpty()) {
            if (connections_.isEmpty()) {
              connections_ = other.connections_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureConnectionsIsMutable();
              connections_.addAll(other.connections_);
            }
            onChanged();
          }
        } else {
          if (!other.connections_.isEmpty()) {
            if (connectionsBuilder_.isEmpty()) {
              connectionsBuilder_.dispose();
              connectionsBuilder_ = null;
              connections_ = other.connections_;
              bitField0_ = (bitField0_ & ~0x00000002);
              connectionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConnectionsFieldBuilder() : null;
            } else {
              connectionsBuilder_.addAllMessages(other.connections_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        for (int i = 0; i < getConnectionsCount(); i++) {
          if (!getConnections(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
            case 18: {
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder subBuilder = stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addConnections(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string text = 1;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
      }
      
      // repeated .Connection connections = 2;
      private java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection> connections_ =
        java.util.Collections.emptyList();
      private void ensureConnectionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          connections_ = new java.util.ArrayList<stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection>(connections_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder> connectionsBuilder_;
      
      public java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection> getConnectionsList() {
        if (connectionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(connections_);
        } else {
          return connectionsBuilder_.getMessageList();
        }
      }
      public int getConnectionsCount() {
        if (connectionsBuilder_ == null) {
          return connections_.size();
        } else {
          return connectionsBuilder_.getCount();
        }
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection getConnections(int index) {
        if (connectionsBuilder_ == null) {
          return connections_.get(index);
        } else {
          return connectionsBuilder_.getMessage(index);
        }
      }
      public Builder setConnections(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection value) {
        if (connectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectionsIsMutable();
          connections_.set(index, value);
          onChanged();
        } else {
          connectionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setConnections(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder builderForValue) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.set(index, builderForValue.build());
          onChanged();
        } else {
          connectionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addConnections(stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection value) {
        if (connectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectionsIsMutable();
          connections_.add(value);
          onChanged();
        } else {
          connectionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addConnections(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection value) {
        if (connectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectionsIsMutable();
          connections_.add(index, value);
          onChanged();
        } else {
          connectionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addConnections(
          stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder builderForValue) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.add(builderForValue.build());
          onChanged();
        } else {
          connectionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addConnections(
          int index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder builderForValue) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.add(index, builderForValue.build());
          onChanged();
        } else {
          connectionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllConnections(
          java.lang.Iterable<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection> values) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          super.addAll(values, connections_);
          onChanged();
        } else {
          connectionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearConnections() {
        if (connectionsBuilder_ == null) {
          connections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          connectionsBuilder_.clear();
        }
        return this;
      }
      public Builder removeConnections(int index) {
        if (connectionsBuilder_ == null) {
          ensureConnectionsIsMutable();
          connections_.remove(index);
          onChanged();
        } else {
          connectionsBuilder_.remove(index);
        }
        return this;
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder getConnectionsBuilder(
          int index) {
        return getConnectionsFieldBuilder().getBuilder(index);
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder getConnectionsOrBuilder(
          int index) {
        if (connectionsBuilder_ == null) {
          return connections_.get(index);  } else {
          return connectionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder> 
           getConnectionsOrBuilderList() {
        if (connectionsBuilder_ != null) {
          return connectionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(connections_);
        }
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder addConnectionsBuilder() {
        return getConnectionsFieldBuilder().addBuilder(
            stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.getDefaultInstance());
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder addConnectionsBuilder(
          int index) {
        return getConnectionsFieldBuilder().addBuilder(
            index, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.getDefaultInstance());
      }
      public java.util.List<stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder> 
           getConnectionsBuilderList() {
        return getConnectionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder> 
          getConnectionsFieldBuilder() {
        if (connectionsBuilder_ == null) {
          connectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection, stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder>(
                  connections_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          connections_ = null;
        }
        return connectionsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ConversationNode)
    }
    
    static {
      defaultInstance = new ConversationNode(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ConversationNode)
  }
  
  public interface ConnectionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ConversationNode node = 1;
    boolean hasNode();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode getNode();
    stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder getNodeOrBuilder();
    
    // required string text = 2;
    boolean hasText();
    String getText();
  }
  public static final class Connection extends
      com.google.protobuf.GeneratedMessage
      implements ConnectionOrBuilder {
    // Use Connection.newBuilder() to construct.
    private Connection(Builder builder) {
      super(builder);
    }
    private Connection(boolean noInit) {}
    
    private static final Connection defaultInstance;
    public static Connection getDefaultInstance() {
      return defaultInstance;
    }
    
    public Connection getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Connection_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Connection_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .ConversationNode node = 1;
    public static final int NODE_FIELD_NUMBER = 1;
    private stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode node_;
    public boolean hasNode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode getNode() {
      return node_;
    }
    public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder getNodeOrBuilder() {
      return node_;
    }
    
    // required string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      node_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getNode().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, node_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, node_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stsquestbuilder.protocolbuffers.ConversationProtobuf.ConnectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Connection_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.internal_static_Connection_fieldAccessorTable;
      }
      
      // Construct using stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNodeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (nodeBuilder_ == null) {
          node_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
        } else {
          nodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.getDescriptor();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection getDefaultInstanceForType() {
        return stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.getDefaultInstance();
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection build() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection buildPartial() {
        stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection result = new stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (nodeBuilder_ == null) {
          result.node_ = node_;
        } else {
          result.node_ = nodeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection) {
          return mergeFrom((stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection other) {
        if (other == stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.getDefaultInstance()) return this;
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNode()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        if (!getNode().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder subBuilder = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.newBuilder();
              if (hasNode()) {
                subBuilder.mergeFrom(getNode());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNode(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ConversationNode node = 1;
      private stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode node_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder> nodeBuilder_;
      public boolean hasNode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode getNode() {
        if (nodeBuilder_ == null) {
          return node_;
        } else {
          return nodeBuilder_.getMessage();
        }
      }
      public Builder setNode(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          nodeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setNode(
          stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          nodeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeNode(stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode value) {
        if (nodeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              node_ != stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance()) {
            node_ =
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.newBuilder(node_).mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          nodeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearNode() {
        if (nodeBuilder_ == null) {
          node_ = stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.getDefaultInstance();
          onChanged();
        } else {
          nodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder getNodeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getNodeFieldBuilder().getBuilder();
      }
      public stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder getNodeOrBuilder() {
        if (nodeBuilder_ != null) {
          return nodeBuilder_.getMessageOrBuilder();
        } else {
          return node_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder> 
          getNodeFieldBuilder() {
        if (nodeBuilder_ == null) {
          nodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder, stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNodeOrBuilder>(
                  node_,
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        return nodeBuilder_;
      }
      
      // required string text = 2;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Connection)
    }
    
    static {
      defaultInstance = new Connection(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Connection)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ConversationPackage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ConversationPackage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Conversation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Conversation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ConversationNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ConversationNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Connection_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Connection_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ConversationProtobuf.proto\";\n\023Conversa" +
      "tionPackage\022$\n\rconversations\030\001 \003(\0132\r.Con" +
      "versation\"N\n\014Conversation\022\037\n\004root\030\001 \002(\0132" +
      "\021.ConversationNode\022\014\n\004name\030\002 \001(\t\022\017\n\007crea" +
      "tor\030\003 \001(\t\"B\n\020ConversationNode\022\014\n\004text\030\001 " +
      "\002(\t\022 \n\013connections\030\002 \003(\0132\013.Connection\";\n" +
      "\nConnection\022\037\n\004node\030\001 \002(\0132\021.Conversation" +
      "Node\022\014\n\004text\030\002 \002(\tB!\n\037stsquestbuilder.pr" +
      "otocolbuffers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ConversationPackage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ConversationPackage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ConversationPackage_descriptor,
              new java.lang.String[] { "Conversations", },
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage.class,
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationPackage.Builder.class);
          internal_static_Conversation_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Conversation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Conversation_descriptor,
              new java.lang.String[] { "Root", "Name", "Creator", },
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.class,
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Conversation.Builder.class);
          internal_static_ConversationNode_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ConversationNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ConversationNode_descriptor,
              new java.lang.String[] { "Text", "Connections", },
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.class,
              stsquestbuilder.protocolbuffers.ConversationProtobuf.ConversationNode.Builder.class);
          internal_static_Connection_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Connection_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Connection_descriptor,
              new java.lang.String[] { "Node", "Text", },
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.class,
              stsquestbuilder.protocolbuffers.ConversationProtobuf.Connection.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
